import Head from 'next/head';
import Navbar from '../Components/Navbar';
import Header from '../Components/Header';
import BlogHeader from '../Components/BlogHeader';
import Footer from '../Components/Footer';

export default function Home() {
  return (
    <div className='flex min-h-screen justify-center items-center'>
      <Head>
        <title>Web-Infosys</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='min-h-screen relative bg-white dark:bg-gray-900'>
        <Navbar/>
        <Header/>
        <BlogHeader/>
        <Footer/>
      </div>
    </div>
  );
}